# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d2c0a3a0bd604242d4f0d1014e9dddbbbc9e4327e7e80eb6dac9fad6d82c0bac5f9d40496933fc273454f5150f50d573a5e5c0437180d3834bd2e4143ec2f9c8

test:
  secret_key_base: 9fcdd938c911f3003bfb998bf939f71313c39f5d7e0bb36ce33b070649b26a35549683b25ece65bcb590167cc7774ee1ebc9041294dff7cdafe2fa299ee4f290

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
